# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f1caaad2df81fc6a647492e7734d176487249be37eeda160efb02c5710b405805c7dcfc2f927d5327b98632d4ec55d75f014e8cb94d0b5df9ccc586989f2abc2

test:
  secret_key_base: 28da7e9f0ccf40b99e071f57205877d63e7b56e1e62c675a994a1b19ae750bc7c7233079f3f1cf92c1b776a619ee627a5c9955802bc67320a5df42db03e51ba3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
